php/phd

- phpdotnet/phd/Config.php
- phpdotnet/phd/Package/PHP/ChunkedXHTML.php
It basically reverts almost all changes made in PR #8. Most of the code
was unused and it failed to copy the stylesheet. This change actually
applies CSS to the generated output.
Also, setting PhD to use PHP.net's CSS was moved inside the PHP Package
so that formats from other packages won't get php.net styling.
Also, fixes bug #67638
CHM format probably require further fixes but I'll commit this changes
first as docs.php.net logs were spammed for months due to this buggy code.
> Fix stylesheet handling for PHP Package

- phpdotnet/phd/Format.php
In PHP 7.2, `count` can only be used with arrays and `Countable` objects. Returning `null` here causes a lot of warnings when building the docs on PHP 7.2.
> Keep the return value to something count-able

- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/Package/PHP/XHTML.php
This change moves the return type name to the right-hand side of the
function/method prototypes, along the same lines as PHP 7 code.
**Before:**
int time ( void )
**After:**
time ( void ) : int
While this is a step towards PHP 7 style, there are still some
departures. Notably:
- No conversion to valid scalar type names is done (e.g. converting
`<type>boolean</type>` to ` : bool`)
- Pseudo-types and other invalid type names are used (e.g. resource,
mixed)
> Render return type in PHP 7 style

- phpdotnet/phd/Render.php
`continue` within a `switch` block works exactly the same as `break` and is normally a mistake. There's no code after the switch so presumably `continue 2` was not intended here, so this PR just changes it to `break` to avoid warnings in PHP 7.3
> Correct continue usage within a switch block

- phpdotnet/phd/Package/Generic/Manpage.php
When I use PhD with PHP 7.4.0, I got the following warning flood.
```
join(): Passing glue string after array is deprecated. Swap the parameters
[01:24:28 - E_DEPRECATED          ] /home/mumumu/.phpenv/versions/7.4.0/lib/php/phpdotnet/phd/Package/Generic/Manpage.php:630
```
Fixed the changed join parameter order, which warning suggests.
> changed join parameter order for PHP 7.4.0

- phpdotnet/phd/Render.php
The `in_array` is used to make it more compatible with https://github.com/php/phd/pull/38/files
This PR removes annoying and inconsistent whitespace before `;` in `<fieldsynopsis>` (properties). E.g. https://www.php.net/manual/en/class.mysqli-result.php
> Remove whitespace before semicolons

- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/Package/PHP/XHTML.php
- phpdotnet/phd/Render.php
This PR removes some unnecessary whitespace characters from the methodsynopses.
So
```php
openssl_csr_sign ( mixed $csr , mixed $cacert , mixed $priv_key , int $days , array $configargs = ? , int $serial = 0 ) : resource
```
becomes
```php
openssl_csr_sign (mixed $csr , mixed $cacert , mixed $priv_key , int $days , array $configargs = ? , int $serial = 0 ): resource
```
Unfortunately, a few unnecessary whitespace characters still remain, and I couldn't yet find out how to remove them as well :/ For me, it looks like some whitespace characters from the XML get rendered directly to the HTML (e.g. around the `,`). Is it possible?
> Reformat methodsynopsis whitespaces

- phpdotnet/phd/Format.php
When I use PhD with PHP 8.0.x, I get the following warning flood.
```
[17:55:07 - E_WARNING             ] /home/mumumu/.phpenv/versions/8.0.1/lib/php/phpdotnet/phd/Format.php:150
phpdotnet\phd\Format::SQLiteExample(): Argument #1 ($context) must be passed by reference, value given
```
I can't find why this warning occurs, but `$this` pseudo value is NOT a reference!! ( https://github.com/php/doc-en/pull/380 )
This PR works on PHP 7.4.x, 8.0.x.
> Fixed E_WARNING "($context) must be passed by reference, value given".

- phpdotnet/phd/Render.php
Union types can get pretty long, so it may make sense to split them
over multiple lines[1]; however, that adds undesired whitespace within
or at the end of the union type.  Thus, we supress this whitespace
generally.
[1] <https://github.com/php/doc-en/pull/783>
> Supress whitespace in type elements

- phpdotnet/phd/Package/Generic/XHTML.php
While "extends" has a special formatting, "implements" is currently missing this. E.g. https://www.php.net/manual/en/class.appenditerator.php
> Fix formatting of the implements keyword

- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/Package/PHP/XHTML.php
- phpdotnet/phd/Render.php
Simple nullable types are now displayed via using "?", while support for intersection types is reintroduced.
Examples for intersection types on the parameter and return type position (even though `X&null` is not valid):
Examples for displaying "simple union types" via using "?":
> Improve the display of union and intersection types

- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/Package/PHP/XHTML.php
> Add support for displaying class/interface on class synopsis pages

- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/Package/PHP/XHTML.php
As noticed in https://github.com/php/phd/pull/52#discussion_r679999018
Requires a followup PR to https://github.com/php/web-php/blob/60a5f74b485075f8fbf2ceef988d343e0157666c/styles/theme-medium.css#L119 in order to display interface names on class synopses the same way as class names.
> Do not render the strong tag unnecessarily

- phpdotnet/phd/Package/PHP/Web.php
- render.php
See also php/doc-base#38 and php/web-php#434
Make the documentation source file information available in generated PHP-Web pages.
> Add source details to PHP-Web pages

- phpdotnet/phd/Format.php
The `example-*` ids, for `example` elements that don't declare their own `xml:id`, are allocated during indexing.  The `N` is just a number that is incremented for each `example` seen (see `Index::format_example()`).
For rendering, the list of ids is fetched from the index to be used in the resulting HTML.  The list needs to be the same `example` elements in the same order for the offset-based lookups (in `Package_Generic_XHTML::format_example()`) to get the correct id.  
The code, before this proposed change, also included the ids for any `informalexample` elements when fetching from the index.  This results in too many items being in the list, so the offset-based lookups when rendering were fetching the wrong ids.
> Fix example id fetching

- .github/workflows/ci.yml
- README
- composer.json
- composer.lock
- phpdotnet/phd/Format.php
- phpdotnet/phd/ObjectStorage.php
- phpdotnet/phd/Render.php
- render.php
- tests/TestRender.php
PhD's `ObjectStorage::attach()` method does not respect the declared return type from its parent class (`SplObjectStorage`): the latter declares the return type as `void`.
This will issue an `E_DEPRECATED` as of PHP 8.1.0. It is currently mitigated via the `#[\ReturnTypeWillChange]` attribute (added in 6c1af76a).
This PR removes that attribute and instead aligns the return type declaration (to return `void`), with associated fixes to not return anything and not try to use a return value.
Since declaring a `void` return type is only allowed as of PHP 7.1.0, this PR raises the minimum required PHP version for phd to that version. Since PHP 7.1 is super ancient and even PHP 7.3 will become EOL in a few weeks (at the time of writing) I'm making the executive decision that requiring 7.1 is …
> make objectstorage::attach() compatible with splobjectstorage::attach()

- phpdotnet/phd/Package/PHP/XHTML.php
In HTML5, `<acronym>` tag is classified as a non-conforming-features.
https://html.spec.whatwg.org/multipage/obsolete.html#non-conforming-features
> replaced <acronym> with <abbr> for HTML5.

- phpdotnet/phd/Package/PHP/Web.php
This pull request
💁‍♂️ For reference, see https://github.com/php/web-php/pull/584.
> Fix: Stop invoking useless function

- phpdotnet/phd/Highlighter.php
Some browsers (notably Firefox ≥ 107) copy these NBSPs verbatim, what causes issues when pasting into text editors/IDE.  Since these NBSPs are generated by `highlight_string()` and there is no option to produce regular spaces instead, we replace them manually.
To preserve the desired code layout, this requires something like <https://github.com/php/web-php/pull/744>.
--- 
Note that this change only affects PHP code samples; there are other cases where PhD renders NBSPs, but these can be addressed when and if needed.
> Fix GH-71: Code examples contain non-breaking spaces

- phpdotnet/phd/Package/Generic/PDF.php
- phpdotnet/phd/Package/Generic/XHTML.php
- Adds cchunk variable for tracking if a classsynopsis is actually an interface
- Render extends instead of implements for interfaces
- Render interface instead of class
After this is merged in, then this PR will render DS as interfaces now: https://github.com/php/doc-en/pull/2549
> Add rendering logic for interfaces

- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/Package/PHP/XHTML.php
- phpdotnet/phd/Render.php
while allowing the old markup to render.
@mallardduck @heiglandreas
I'll push an example of some doc-en changes that would render this markup.
From my testing (which is not the most extensive) nothing is broken.
> Add support for rendering more logical classsynopsis markup

- render.php
I'm getting
```
[18:56:04 - E_WARNING             ] /home/niels/php-docs/phd/phpdotnet/phd/Render.php:49
XMLReader::read(): /home/niels/php-docs/doc-base/.manual.xml:321087: parser error : internal error: Huge input lookup
[18:56:04 - E_WARNING             ] /home/niels/php-docs/phd/phpdotnet/phd/Render.php:49
XMLReader::read():   <par
[18:56:04 - E_WARNING             ] /home/niels/php-docs/phd/phpdotnet/phd/Render.php:49
XMLReader::read():   ^
```
if I don't pass this option, causing the docs build to fail.
> Set LIBXML_PARSEHUGE

- phpdotnet/phd/Highlighter.php
In a second step the CSS will need to be adjusted.
------------
Actual newlines will be replaced by `<br />` during highlighting and the `\n` in the boilerplate conflicts with `white-space: pre;`.
see php/doc-en#2648
> Drop `\n` when highlighting

- phpdotnet/phd/Index.php
- phpdotnet/phd/Package/Generic/TocFeed.php
- phpdotnet/phd/Package/PHP/XHTML.php
This would allow us to use more conformant DocBook markup in the docs
This ignores the PEAR and Generic/XHTML renderers.
> Support standard DocBook annotations XML attribute for chunking

- phpdotnet/phd/Index.php
- phpdotnet/phd/Package/PHP/TocFeed.php
- phpdotnet/phd/Package/PHP/XHTML.php
This is one of the last remaining stepping stone to make the PHP documentation use the standard DocBook spec.
> Add support to render refentry tags as class and variable wrappers

- phpdotnet/phd/Index.php
- phpdotnet/phd/Render.php
Fix #87 
btw, there seems to be a problem with all the `<row xml:id` links.
e,g. https://www.php.net/manual/en/tokens.php
The `__TRAIT__` link is the current page and is correct after the fix.
--- 
Sorry, I committed to master by mistake. 😅 934be12873ce67e9db19586919afb2a45d791c91
> Fix constants link broken

- phpdotnet/phd/Package/PHP/ChunkedXHTML.php
- phpdotnet/phd/Package/PHP/XHTML.php
Let the `--css` option override the default stylesheets for all PHP XHTML-based formats. Closes #70.
Phd's `--css` option allows to pass stylesheets to the rendered formats. However, in the constructor of the `PHP_ChunkedXHTML` format two stylesheets from `php.net` are added to every rendering in this format. 
This PR changes this behaviour so that the hardcoded stylesheets are only added if there are no stylesheets passed in from the command line and it applies this to all of the XHTML-based format in the PHP package. 
The default behavior (ie. without the `--css` option) does not change for the `PHP_ChunkedXHTML` format.
> Override hardcoded stylesheets in PHP XHTML formats

- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/Render.php
- tests/php/type_rendering_001.phpt
- tests/php/type_rendering_002.phpt
- tests/php/type_rendering_003.phpt
- tests/xhtml/data/simplelist.xml
- tests/xhtml/simplelist_001.phpt
- tests/xhtml/whitespace_formatting_001.phpt
Implement `type` and `columns` attributes of `<simplelist>`. Preserve backward compatibility by still using `<ul>` and `<li>` elements if no `type` is specified, ie. by not defaulting to `vert` as described [here](https://tdg.docbook.org/tdg/4.5/simplelist). See the included test for examples.
Closes #83, supersedes #84 and depends on #95 for proper formatting of whitespace.
Works on the same principle as parameter and return type rendering, ie. storing values, discarding output and processing when the appropriate section is closed.
The main method for processing `<simplelist>` is rather big and ugly so I'd appreciate all feedback on how to improve it.
> Implement simplelist attributes

- phpdotnet/phd/Package/Generic/XHTML.php
- tests/TestRender.php
- tests/php/constant_links_001.phpt
- tests/php/data/constant_links.xml
Add links to constants with IDs in the following two standard formats (`xml:id` doesn't have to be on the `<constant>` element):
```xml
<constant xml:id="extension-namespace-or-classname.constants.name-of-constant">
Extension\Namespace\Or\ClassName::NAME_OF_CONSTANT
</constant>
<constant xml:id="constant.name-of-constant">
NAME_OF_CONSTANT
</constant>
```
Please note that there is a large number of constants not using one of these standard formats.
> Add links to constants

- .github/workflows/test.yml
- tests/xhtml/001.phpt
- tests/xhtml/data/001-1.xml
Run the few available tests on each push to the repo.
This could be used as a basis for gradually adding tests to at least the format used to generate the official docs (PHP package's XHTML format if I'm not mistaken).
> Run tests on pull requests

- phpdotnet/phd/Package/Generic/XHTML.php
- tests/package/php/constant_links_001.phpt
- tests/package/php/data/constant_links.xml
Trim leading and trailing underscores in constant IDs. 
Add test cases.
Used for magic constants, FFI's `__BIGGEST_ALIGNMENT__` and the global `__COMPILER_HALT_OFFSET__` constants.
> Trim leading and trailing underscores in constant IDs

- .github/workflows/ci.yml
Change the PHP versions for the smoke tests to 8.0 and above. As PHP 8.0+ features are already in use in the codebase (e.g: `match`, `str_contains()`, etc.) this should not be an issue.
> Bump smoke test version to 8.0+

- phpdotnet/phd/Options/Handler.php
- phpdotnet/phd/Options/Interface.php
- phpdotnet/phd/Options/Parser.php
- render.php
Most of this PR adds dependencies of `Options_Parser` as constructor parameters (and injects them from `render.php`) and adds parameter and return types to `Options_Handler`, `Options_Interface` and `Options_Parser`.
There are six smaller commits in this PR and it's probably easier to review it commit by commit.
> Refactor Options Handler, Interface and Parser

- phpdotnet/phd/Autoloader.php
- phpdotnet/phd/Options/Handler.php
- phpdotnet/phd/Options/Parser.php
- render.php
- tests/options/default_handler_001.phpt
- tests/options/default_handler_002.phpt
- tests/options/default_handler_003.phpt
- tests/options/default_handler_004.phpt
- tests/options/default_handler_005.phpt
- tests/options/default_handler_006.phpt
- tests/options/default_handler_007.phpt
- tests/options/default_handler_008.phpt
- tests/options/default_handler_009.phpt
- tests/options/default_handler_010.phpt
- tests/setup.php
This PR includes the followings:
- remove all direct setting of `Config` from the default `Options_Handler` and return an array of parsed options instead. Add return type declarations to each method returning an array
- inject dependencies through `Options_Handler`'s constructor in `render.php`
- refactor a few files to allow them to be used from tests
- add tests for the default `Options_Handler` and `Options_Parser`
- fix inconsistent short and long option required/optional flags in `Options_Handler`
> Refactor Options Parser and default Options Handler

- phpdotnet/phd/Reader.php
- phpdotnet/phd/Reader/Partial.php
- render.php
- tests/reader/partial_reader_001.phpt
- tests/reader/reader_001.phpt
Inject dependencies through the constructor of `Reader_Partial`, add parameter and return type hints and add tests for both `Reader`s.
> Refactor Reader and Reader_Partial

- phpdotnet/phd/Package/PHP/Web.php
Pass the various setup variables to the footer so that the contribution links can be moved there in `web-php`.
> Pass setup to page footer

- phpdotnet/phd/Index.php
- phpdotnet/phd/IndexRepository.php
- phpdotnet/phd/TestRender.php
- phpdotnet/phd/functions.php
- render.php
- tests/index/bug_GH-98.phpt
- tests/index/data/indexing_001.xml
- tests/index/indexing_001.phpt
This PR is a minimal refactoring of `Index` to move its dependencies out of the class and inject them through the constructor.
The changes are:
- move `requireIndexing()` method out of `Index` into a global function that receives all its dependencies through parameters
- add a new `IndexRepository` class that handles all database access for `Index`, refactor `Index` to receive an object of this class as a constructor dependency and to pass raw data to it (i.e. data not containing SQL statements)
- add basic indexing test
- fix existing test that uses indexing to use `IndexRepository`
> Refactor Index

- phpdotnet/phd/Config.php
- phpdotnet/phd/Package/PHP/Web.php
- render.php
Load file modification history from file and add it to PHP documentation pages. This data will be used to add last commit date/time and author, as well as a list of all contributors to the each page.
Needs https://github.com/php/doc-base/pull/120 for it to work.
> Add file modification history to PHP doc pages

- phpdotnet/phd/Package/PHP/XHTML.php
- tests/package/php/faq001.phpt
Add title color to h1 title elements such as the titles of sections under Appendices in the manual (e.g the title of https://www.php.net/manual/en/history.php).
> Add title color to h1 title elements

- phpdotnet/phd/Format.php
- phpdotnet/phd/functions.php
- render.php
Use the same indexing database in every part of PhD by always retrieving it from `indexcache` and always set `indexcache` before any indexing or rendering is done in `render.php`.
> Use the same indexing database throughout

- phpdotnet/phd/Package/Generic/XHTML.php
- tests/package/generic/data/simplelist.xml
- tests/package/generic/simplelist_001.phpt
Render elements in `<simplelist>` `<member>`s correctly by buffering all output in a `<member>` element.
> Render elements in simplelist members correctly

- phpdotnet/phd/Options/Handler.php
- render.php
Remove output directory creation from render.php as this is already done in `Config` when setting the output directory. Move the appropriate checks and errors/warnings from `render.php` to `Config`.
> Remove output directory creation from render.php

- package.xml
I cannot run phd of the latest HEAD.
This is because `IndexRepository.php` is added in https://github.com/php/phd/commit/26bf0c610a61160a3e4cc91e88ed68e0f179e28f.
```
$ phd -f xhtml -L ja -P PHP -d doc-base/.manual.xml
[12:29:14 - Indexing              ] Indexing...
[12:29:14 - E_USER_ERROR          ] /home/mumumu/.phpenv/versions/8.3.6/lib/php/phpdotnet/phd/Autoloader.php:26
Cannot find file for phpdotnet\phd\IndexRepository: /home/mumumu/.phpenv/versions/8.3.6/lib/php/phpdotnet/phd/IndexRepository.php
```
When refactoring to organize files, please also pay attention to the entries in package.xml.
> Added IndexRepository.php entry for pear install command

- .github/workflows/full_render_doc-en_test.yml
This could be an additional test for testing PhD with a full render of the `doc-en` repo.
> Full doc-en render test

- phpdotnet/phd/Format.php
- phpdotnet/phd/IndexRepository.php
- phpdotnet/phd/functions.php
- render.php
Move all database access code to `IndexRepository` and use the same `IndexRepository` instance everywhere.
> Move all database access code to IndexRepository

- phpdotnet/phd/Package/Generic/XHTML.php
- tests/package/generic/attribute_formatting_001.phpt
- tests/package/generic/data/attribute_formatting_001.xml
This PR adds support for attributes in the format described in [this comment](https://github.com/php/doc-en/pull/3385#discussion_r1601401758) and generates links to the documentation pages of known predefined attributes.
*Edit:*
As a side note, there are 129 additional attributes in `php-src` stub files that are not documented in `doc-en`.
> Add Attribute linking

- phpdotnet/phd/Format.php
- phpdotnet/phd/IndexRepository.php
- phpdotnet/phd/functions.php
- render.php
- tests/render/data/render_001.xml
- tests/render/render_001.phpt
Move all database access to IndexRepository.
Use the same database during the entire indexing-rendering process. 
Add a simple smoke test for render.php.
This PR is the same as #120 with the following exceptions:
- `functions.php`'s `requireIndexing()` is now checking whether `Config`'s `indexcache` exists (where the indexing database used everywhere is stored in and after this PR), therefore the `SQLite` database parameter has been removed
- `indexcache` is set for every run so setting it after indexing has been removed in `render.php`
- added the `$config` parameter (of type `Config`) to `make_reader()` in `render.php`, calling it with `new Config` arguments at call sites (this was the issue that broke the builds in the last PR, thanks to @sy-records for pointing it out)
- added a smoke …
> Move all database access to IndexRepository

- render.php
Remove superfluous database initialization as database is already initialized during the initialization of Indexing.
> Remove superfluous database initialization

- phpdotnet/phd/IndexRepository.php
- phpdotnet/phd/Package/Generic/PDF.php
- phpdotnet/phd/Package/PHP/XHTML.php
- tests/bug_doc-en_GH-3353.phpt
- tests/data/bug_doc-en_GH-3353.xml
Closes https://github.com/php/doc-en/issues/3353.
When the list of `refentry`s (functions and methods) is retrieved from the indexing database the characters `_`, `::` and `->` in their names were replaced by `-` before storing them in the array `$ref` in `Format.php`. As this array is used to generate the links to and the index list of functions/methods, functions and methods with the same name after replacing the before mentioned characters (e.g. `finfo_buffer()`/`finfo::buffer()`, `finfo_file()`/`finfo::file()`, etc.) were overwriting each other's reference entries in memory (in the `$ref` array).
Fix this by not replacing the above listed characters.
> Fix GH-3353 incorrect function tag linking

- phpdotnet/phd/IndexRepository.php
`refentry` names are taken from xml IDs and stored in the database during indexing. These are then retrieved and used for linking to functions and methods. Do not use `html_entity_decode()` on these names as these IDs should not have entities in them to begin with. This change aligns this function with the function/method linking functions that only do `strtolower()` as well.
There is no test for this PR but I've ran the a full render of `doc-en` with and without this change and there were zero diffs for the ~12k generated files.
> Remove html_entity_decode() when getting refentry names from the database

- phpdotnet/phd/Index.php
`ReaderKeeper` is a global static object wrapper around an array that contains the active `Reader` and is used by three `Format`s to read the contents of certain tags as string, XML or return it as a DOM Node. 
This PR removes `ReaderKeeper` from the `Index` `Format` by delaying writing the long and short descriptions, and the changelog tables until after the appropriate tags are closed. This is done in a similar way to how method parameters are rendered, ie. by keeping everything inside the tag in temporary variables and processing them when the tag is closed.
There is no test for this PR but I've done a full render of `doc-en` with and without these changes and there are zero diffs for the ~12k files generated.
> Remove ReaderKeeper from Index

- phpdotnet/phd/Index.php
- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/Package/PHP/XHTML.php
- tests/package/php/class_rendering_001.phpt
- tests/package/php/class_rendering_002.phpt
- tests/package/php/class_rendering_003.phpt
- tests/package/php/data/class_rendering_001.xml
- tests/package/php/data/class_rendering_002.xml
- tests/package/php/data/exception_rendering_001.xml
- tests/package/php/data/exception_rendering_002.xml
- tests/package/php/exception_rendering_001.phpt
- tests/package/php/exception_rendering_002.phpt
- tests/package/php/exception_rendering_003.phpt
This PR adds support for the new markup for classes and exceptions. Rendering `doc-en` with the old markup with and without these changes, and the new markup with these changes showed zero diffs.
> DocBook 5.2 class and exception markup migration

- phpdotnet/phd/Package/Generic/XHTML.php
- tests/package/generic/attribute_formatting_001.phpt
- tests/package/generic/attribute_formatting_002.phpt
- tests/package/generic/data/attribute_formatting_001.xml
- tests/package/generic/data/attribute_formatting_002.xml
Enable rendering of attributes for classes, exceptions, interfaces, methods and functions. The implementation feels a little off but it seems to work as intended (see attached test `attribute_formatting_002.phpt`).
I've also found a mistake I've made in the test `attribute_formatting_001.phpt` where the parameter attribute was outside of the `<methodparam>` element. I've corrected this by moving the attribute inside the element.
> Add non-parameter attribute rendering

- phpdotnet/phd/Index.php
- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/TestRender.php
- tests/bug_doc-en_GH-3428.phpt
- tests/data/bug_doc-en_GH-3428.xml
Replace static example element counter with class properties in `Index` and `generic XHTML`. Add tests.
Refactor `TestRender` so that it can render multiple formats.
Closes [doc-en #3428](https://github.com/php/doc-en/issues/3428).
> Fix doc-en GH-3428

- phpdotnet/phd/Package/Generic/XHTML.php
- tests/package/generic/attribute_formatting_003.phpt
- tests/package/generic/data/attribute_formatting_003.xml
Add class property and constant attribute rendering support.
This, the [parameter](#127) and the [class, method and function](#135) attribute PRs together close https://github.com/php/doc-en/issues/3405.
> Add property and constant attribute rendering

- phpdotnet/phd/Autoloader.php
- render.php
- tests/autoloader/autoloader_001.phpt
- tests/autoloader/external_directory_test/phpdotnet/phd/TestFormat.php
- tests/setup.php
Remove `Config from Autoloader` by replacing it with a static array and a setter method. 
Update `render.php` and `setup.php` to pass package directories to `Autoloader`. 
Add test.
> Remove Config from Autoloader

- phpdotnet/phd/Index.php
- phpdotnet/phd/IndexRepository.php
- phpdotnet/phd/PI/PHPDOCHandler.php
- phpdotnet/phd/TestIndex.php
- tests/bug_GH-87.phpt
- tests/data/bug_GH-87.xml
- tests/index/data/indexing_001.xml
- tests/index/indexing_001.phpt
https://www.php.net/manual/en/doc.changelog.php is empty because this was backwards and changelog entries weren't actually being indexed.
> Fix element map so changelog rows are handled correctly

- phpdotnet/phd/Highlighter.php
PHP 8.3 changed the details of highlighting PHP code[1], basically like we did[2] at roughly the same time.  However, both don't work well together, so we avoid that.
[1] <https://github.com/php/php-src/pull/11913>
[2] <https://github.com/php/phd/pull/79>
---
The following is certainly not desireable:
cc @TimWolla, @kamil-tekiela
> Fix PHP highlighting for PHP ≥ 8.3

- phpdotnet/phd/Package/PHP/Web.php
> [!NOTE]
> This is a companion PR to https://github.com/php/web-php/pull/1084, but it is not dependent on it and can be merged independently.
PHD index entries can have both short (sdesc) and long (ldesc) descriptions. Often, the short description is empty, leading to the current fallback mechanism in `getShortDescription` and `getLongDescription`:
```php
// phpdotnet/phd/Format.php
final public function getLongDescription($id, &$isLDesc = null) {
if ($this->indexes[$id]["ldesc"]) {
$isLDesc = true;
return $this->indexes[$id]["ldesc"];
} else {
$isLDesc = false;
return $this->indexes[$id]["sdesc"];
}
}
final public function getShortDescription($id, &$isSDesc = null) {
if ($this->indexes[$id]["sdesc"]) {
$isSDesc = true;
return $this->indexes[$id]["sdesc"];
} else {
$isSDesc = false; …
```
> Improve search index generation for PHP.net

- composer.json
- composer.lock
The code already uses `match` construct so the minimum version must be PHP 8.0
> Bump PHP version to 8.0.0

- phpdotnet/phd/Config.php
- phpdotnet/phd/constants.php
- phpdotnet/phd/functions.php
- render.php
- tests/setup.php
Move all constant definitions to a dedicated file and include that in the main and test renderer files.
> Move constant definitions to a dedicated file

- README.md
- composer.json
- composer.lock
The code uses the `never` type which was introduced in PHP 8.1 so we need to bump the minimum version.
> Bump minimum PHP version to 8.1

- phpdotnet/phd/Autoloader.php
- phpdotnet/phd/Highlighter.php
- phpdotnet/phd/Options/Handler.php
- phpdotnet/phd/Package/Generic/ChunkedXHTML.php
- phpdotnet/phd/Package/Generic/Manpage.php
- phpdotnet/phd/Package/Generic/TocFeed.php
- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/Package/IDE/Base.php
- phpdotnet/phd/Package/PEAR/CHM.php
- phpdotnet/phd/Package/PEAR/ChunkedXHTML.php
- phpdotnet/phd/Package/PHP/BigPDF.php
- phpdotnet/phd/Package/PHP/EnhancedCHM.php
- phpdotnet/phd/Package/PHP/HowTo.php
- phpdotnet/phd/Package/PHP/PDF.php
- phpdotnet/phd/Package/PHP/Web.php
- phpdotnet/phd/Package/PHP/XHTML.php
- render.php
Use `trigger_error()` for triggering the error handler for errors instead of the custom function `v()`. `vsprintf()` is used with some errors as this function is used in function `v()` where formatted strings are being passed to the error handler.
I think this change makes sense semantically and will help with separating the intertwined error handling/info message printing of `PhD`.
> Use trigger_error() for errors

- phpdotnet/phd/Package/PHP/Web.php
Fixes #159
This commit enhances the search index generation process by providing more meaningful subtitles (descriptions) for entries that lack a parent `<book>` element.
id | title | current subtitle | new subtitle
--- | --- | --- | ---
copyright | Copyright | Copyright | PHP Manual
preface | Preface | Preface | PHP Manual
... | ... | ... | ...
book.opcache | OPcache | OPcache | Affecting PHP's Behaviour
refs.basic.php | Affecting PHP's Behaviour | Affecting PHP's Behaviour | Function Reference
... | ... | ... | ...
<details><summary>View the entire table</summary>
id | title | current subtitle | new subtitle
--- | --- | --- | ---
copyright | Copyright | Copyright | PHP Manual
preface | Preface | Preface | PHP Manual
getting-started | Getting Started | Getting Started | PHP Manual …
> Fix search index for entries without parent book

- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/Render.php
- tests/package/php/constant_links_001.phpt
- tests/package/php/data/constant_links.xml
Add links to constants with replaceable tags by processing them when the constant tag is being closed. Also add a test.
This currently only works with one set of `<replaceable>` tags per constant (due to issues making the regex non-greedy). In practice, this shouldn't be an issue as we have no constants with more than one set of these tags.
The implementation feels a little hacky but more or less matches the processing of all other tags where post-processing is needed (all the class-based `synposis*` tags and their children).
> Add links to constants with replaceable tags

- phpdotnet/phd/Package/Generic/XHTML.php
- tests/package/php/data/property_linking.xml
- tests/package/php/property_linking.phpt
Add linking to `<property>` elements. 
This works the same way `<constant>` tag linking works and is based on the understanding that `<property>` elements are only to be used for class properties. As with constant linking, property linking  requires the `<property>` elements to include a FQN (eg. `<property>DOMNameSpaceNode::$parentElement</property>` instead of just `<property>$parentElement</property>`) and an element with the appropriate xml ID (eg. `<varlistentry xml:id="domnamespacenode.props.parentelement">`).
Reference issue: https://github.com/php/phd/issues/164
> Add property linking

- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/Package/PHP/XHTML.php
- tests/package/php/class_and_method_link_rendering_001.phpt
- tests/package/php/constant_links_001.phpt
- tests/package/php/data/class_and_method_link_rendering_001.xml
- tests/package/php/data/constant_links.xml
- tests/package/php/data/property_linking.xml
- tests/package/php/property_linking.phpt
Minimal fix for FQN class and method/function linking not working. Closes GH-170.
> Fix FQN class, method, property and constant linking

- phpdotnet/phd/Autoloader.php
- phpdotnet/phd/Config.php
- phpdotnet/phd/Format.php
- phpdotnet/phd/Format/Abstract/PDF.php
- phpdotnet/phd/Highlighter.php
- phpdotnet/phd/Highlighter/GeSHi.php
- phpdotnet/phd/Highlighter/GeSHi11x.php
- phpdotnet/phd/Options/Handler.php
- phpdotnet/phd/Package/Generic/TocFeed.php
- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/Package/IDE/API.php
- phpdotnet/phd/Package/IDE/API/Function.php
- phpdotnet/phd/Package/IDE/API/Param.php
- phpdotnet/phd/Package/IDE/Base.php
- phpdotnet/phd/Package/IDE/demo.php
- phpdotnet/phd/Package/PEAR/CHM.php
- phpdotnet/phd/Package/PEAR/XHTML.php
- phpdotnet/phd/Package/PHP/EnhancedCHM.php
- phpdotnet/phd/Package/PHP/Manpage.php
- phpdotnet/phd/Package/PHP/XHTML.php
- phpdotnet/phd/ReaderKeeper.php
This PR includes a lot of commits with minor issues found with static analysis. Please review commit by commit.
> Minor cleanup

- phpdotnet/phd/Index.php
- phpdotnet/phd/Package/PHP/XHTML.php
- tests/package/php/data/enum_link_rendering.xml
- tests/package/php/enum_link_rendering.phpt
In my local:
Actually, it would be nice to be able to link `RoundingMode::HalfAwayFromZero` as well, but that might be a good idea to wait for a follow-up.
> Add support enum links

- phpdotnet/phd/Package/PHP/XHTML.php
close https://github.com/php/doc-en/issues/4371
close https://github.com/php/phd/issues/193
> Support enum display version info

- phpdotnet/phd/Format/Abstract/XHTML.php
- phpdotnet/phd/Package/Generic/XHTML.php
- phpdotnet/phd/Package/PHP/XHTML.php
This goes hand in hand with https://github.com/php/web-php/pull/1228 and the changes I pushed to `doc-en` just now.
> Interactive annotations
